travis:
  secure:
    BINSTAR_TOKEN: PdLiSyJ+Aho+juf1lagxL6Key2q5YvPF7MU/RbiDl5H85xnPdzPRRpBVZBp4a61+lnZARZ+YViU5Jtmrq57/2IEYBAljo4Kjg/Kiz6U04Qidp+LeoET4gp2ATiJnfY70Adh/+ul6qnvQpaPL8/ytKbshLWYjl0DDYRpQfx6w45etH4K6jv1sLPjJOVIwoI54KmeU+sipD6ABi3uxg3KGCVqT2jQM0iZSu1uVhM9id3pUSwkIenlWyId1htLepdAJ7Dll4jk7tp/OkH15vhVb2c4k1QlroQSHxhRFrSgh5rZFwzJRKuQOLwd+iXL5hR39aCSTjfhQswL+Ey4qv7A+Ttm2Px+743R3GJo+oR+9kmXTW7CiLsSZWXFjhpZGngBAmqKY214Nu9OaeyrM/bjno3dF9QZqpxdhvehBcPa+tw7svva4036CcL/GjKFvQzIDZB8gIvKdJJ6ZG00+mz1vod7djySq7K35fJJbuWi3O21FD1Iln/DCdz9VFfW21yIsZAqtA7SFT+JJWCIeordf5pW7royoyU8S77jYNXICXb0gBO1Z+0qlv2iEtyCiyFpKOWORTwn8Ql/B+vgQgbqoNgKNWKaZ2iZJEEO0lnt4c6jUn5Lgg+YDUNCizJVtQ39plA4X5NWcDWjTg2pAqKnxGT2wtWNjBkgs5Fb2Lk5MWew=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
