travis:
  secure:
    BINSTAR_TOKEN: xSkXFlafHAgA1LQEM5I6o2BqnQB5USttTzkPUo0vdWSkcqJVFm6VldvaXriQcBSpBl4acYlrjSEOlXj6miQEqRNVQo/QnKmtAfp0Uczep7DVRuXBV7C3l/70j9OA7HzJ4pZAfdhXiX5Ady4K+lCJMcLLc4X7VAHhIhfY1oRjh5eYiq2ENy7p8dWYI2EmvU5vlAkjya4u3vAAl/KiyPuTZxmknpK4G4GXBPQJBFFQzSQftlxRWDCWbWT/gSfZbgzx/+0fmtl0b51kIIfAgCuWusFwObDSklV7GrKWU7KGmYDAO6rMaNEUrFDQ4n72VlkwzaFUJZGC+6gNhhIT86kBYZJC+JCQ0eq8LnJ33G/VNEOZY2ZliHa82jP15T/PGO37YcMEcNMZfytFom9UT4YLLz6e1FF6N8L3FLfw/9qj4r+/XhirOs13oJUyO4YdayX7DjRLrNiFJAUSWrC+TSA419SnrKj+512zy3/FcVYyKHQbrDECC+5WK9a4ynGDlNtQcUWO3G4QOqPJVla0IMzlAzDnq0KfcyiPpBDbQ4TdYtqRUhDrrOelrADlm5qQFToYx65kSLrhEywHu7Spf9qE29b6D8vZTa0F6fADUW8/3O1lPkXM3tsnjWX+/mREmdpFp/5XwuWOZa5iMIF0pEfI3KihI7VnTX4OjzqDyG6WyAI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
