travis:
  secure:
    BINSTAR_TOKEN: dRNlb8KeZCgHTZmG2angJXV/xtmUohsjA0jplmvJE6/K/+t2vKg0CiBEYGd+uPJAbsVg8xDH8p0WUFMsI7i1k2Ng8yJSUtW96Kpi0705J0JKPRnUX2O75bCUk2uZCoL3CxWKxMyUCihrlvWI31kMVUywsbSbOE1SfUNSgyBd0fYxJtK6KGmVFIQ6Ntye3X7bUelpCqLGTJPFXlYBWevR+jkPW4+Zer0Uj9tpgb0vZOI7qkwn6lTcw+L5kjzkz3L/Co4qWMoFbFN54uv1XH43p4hFwCzt8DuUpKwU4aRFZHBfE4kpnMRUfm2NA3dziwns+YK2EGxZ9YibeqHSAC/nnl1aNWpf+d/vQAJ0GuNcr/xoSsGlu2bnruozfHA4KWAkVtwIBXc/2Vv5bnKKVoUkJtY2GlzWZ+Ch/K0kjR/6Nuq+7GfTlExfbaGgUjV2oWgnnx8BXfbgptL5wyzuaflWIzM1ntklvDzXQjQe6S7Q5sIm1rj8HBhXjvDHXfu+cr8Cx6OkjsZrVxLiYq3gKHUTCwTtW1ZI/p81ZVDCqaCSfWcyVSSo+bXcgY/Br93dwm4Fin12Ec5dWa4gjNcGKUtmjdqzhdp9wlB4qaTpQoV6E/WZToYcZfty52mlDhST2La+D2qXB5Yp6C7LmKiEvmMpmOwwYcXZg4RVqZdQ4EJHHK8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
