travis:
  secure:
    BINSTAR_TOKEN: jt2c8ClqiqICxspKJlGCrgbZx0OcDagu8onObEmwlOi/PyxJsxZntY5SS/Tob8QTYPgNsbZXXWCvs7vTrXeaJiUupjjzD4amUbmTgG7jAFEg6JmLImZj2DORlIQALkCSPi8D02W6kYQ3ktAkkXd8MMYTKRKjd1oP4mdw5ltdcfzDMWNoP4cLBFmuB8D4TqhTkMpMywVyAYp2ZwqrYDJzQkqXoa+eaPmmljrVZXbM5EXwNwzQRbEDI+q0wxamoy0KJt4tu//nw8H52cyGZwnZykPnOiIQvBE6QE3MdZ/gA4sH+OPHtit2ycfTLbZQmCX3XNgloE8Efa2lG3pZ0gTmDn2yEhOuDtNYyAIxeHonC0egc2ly/CktndKzlAbPXkXfgS4d+o+nFb7NFPvKc7h+jtbJnOlgAQm1PIQoZ420TiqsNubZHG27Ee3ff1qQGq9mhiQyufJCUUuYk2ynqYbHohnMTiAz77qs773IYY3i7gQYzyjg3LHDw1McPd2mKyR5QkIWFYa8RJqPK2CDdSHhKIKp+UQ7r0vxloiPVilpxCNz6e2bpnw2JRe3YZeYkEApkaE7freZr9wNtI+9PqvieROCES5ahRm8+f8cQw4M27gC+2vjTWR04C/4lviieWGRAXmna8lsAVyjSCWeRZR6k4hdM/XCVxzf2yH7OrbcQGE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
